# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ett.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'ett.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tett.proto\x12\x07\x65xample\x1a\x1cgoogle/api/annotations.proto\x1a google/protobuf/descriptor.proto\"\x1c\n\x0e\x45xampleRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\"\n\x0f\x45xampleResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2k\n\x0e\x45xampleService\x12Y\n\nGetExample\x12\x17.example.ExampleRequest\x1a\x18.example.ExampleResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/example/{id}:2\n\npy_package\x12\x1c.google.protobuf.FileOptions\x18\xa2\x90\x03 \x01(\tB\t\x92\x82\x19\x05protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ett_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\222\202\031\005proto'
  _globals['_EXAMPLESERVICE'].methods_by_name['GetExample']._loaded_options = None
  _globals['_EXAMPLESERVICE'].methods_by_name['GetExample']._serialized_options = b'\202\323\344\223\002\022\022\020/v1/example/{id}'
  _globals['_EXAMPLEREQUEST']._serialized_start=86
  _globals['_EXAMPLEREQUEST']._serialized_end=114
  _globals['_EXAMPLERESPONSE']._serialized_start=116
  _globals['_EXAMPLERESPONSE']._serialized_end=150
  _globals['_EXAMPLESERVICE']._serialized_start=152
  _globals['_EXAMPLESERVICE']._serialized_end=259
# @@protoc_insertion_point(module_scope)
